services:
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    profiles:
      - internal-redis

  api:
    container_name: api
    image: ragpi/ragpi:${API_VERSION:-latest}
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    env_file: .env

  task-worker:
    container_name: task-worker
    image: ragpi/ragpi:${API_VERSION:-latest}
    command: celery --app=src.celery.celery_app worker --concurrency=2 --max-tasks-per-child=1 --loglevel=INFO
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    env_file: .env

volumes:
  redis-data: